<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPQpNx6f\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPQpNx6f/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPQpNx6f.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPQpNx6f\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPQpNx6f\App_KernelDevDebugContainer([
    'container.build_hash' => 'PQpNx6f',
    'container.build_id' => '9a486563',
    'container.build_time' => 1680566356,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPQpNx6f');
